# Generated by Django 3.2.25 on 2025-06-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accomodation',
            new_name='Accommodation',
        ),
        migrations.RenameField(
            model_name='accommodation',
            old_name='avialability',
            new_name='availability',
        ),
    ]
